name: PrivacyGuard CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    - name: Install dependencies
      run: npm install --legacy-peer-deps --no-workspaces --prefix frontend || true
    - name: Build frontend
      working-directory: ./frontend
      run: npm install --legacy-peer-deps && npm run build
