name: PrivacyGuard CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install and Build Frontend
      run: |
        rm package.json
        cd frontend
        npm install --no-package-lock --legacy-peer-deps
        npm run build
